name: Deploy Angular Frontend

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Which frontend to deploy"
        required: true
        type: choice
        options:
          - submission-portal
          - admin-portal

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            if [ "${{ github.event.inputs.project }}" = "submission-portal" ]; then
              submission-portal/package-lock.json
            else
              repair-request-portal/package-lock.json
            fi

      - name: Install dependencies
        run: npm ci
        working-directory: |
          if [ "${{ github.event.inputs.project }}" = "submission-portal" ]; then
            submission-portal
          else
            repair-request-portal
          fi

      - name: Build Angular project
        run: |
          if [ "${{ github.event.inputs.project }}" = "submission-portal" ]; then
            npm run build:submission-portal
          else
            npm run build:admin-portal
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          if [ "${{ github.event.inputs.project }}" = "submission-portal" ]; then
            aws s3 sync submission-portal/dist/submission-portal/browser s3://renocar-zgloszenie.pl --delete
          else
            aws s3 sync repair-request-portal/dist/repair-request-portal/browser s3://portal.renocar-zgloszenie.pl --delete
          fi

      - name: CloudFront Invalidation
        run: |
          if [ "${{ github.event.inputs.project }}" = "submission-portal" ]; then
            aws cloudfront create-invalidation \
              --distribution-id ${{ secrets.SUBMISSION_PORTAL_DISTRIBUTION_ID }} \
              --paths "/*"
          else
            aws cloudfront create-invalidation \
              --distribution-id ${{ secrets.ADMIN_PORTAL_DISTRIBUTION_ID }} \
              --paths "/*"
          fi
